apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-faker
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: faker
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: faker
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always # usually not required in production, but for this local setup it is required
          args: ['faker']
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: FAKER_TARGET
              value: "http://{{ include "chart.fullname" . }}:{{ .Values.httpPort}}"
